---
title: "Phytoplankton Analyses"
author: "Chris Madsen"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
editor_options: 
  chunk_output_type: console
---

<style>
.container-fluid .crosstalk-bscols {    
/*push content away from far right and left edges*/
  margin-right: 0px;
  margin-left: 0px;
}
</style>

```{r setup, include=FALSE}
# This block of code loads in packages that we will use, sets knitting options (echo = FALSE, warning = F, etc.), brings in the CO2 dataset and modifies it a bit, and then creates a crosstalk object (specifically, a SharedData R6 object)
library(flexdashboard)
library(crosstalk)
library(tidyverse)
library(plotly)

# If you haven't installed the summary widget code before,
# please nab it from github by running the line below:
# devtools::install_github("kent37/summarywidget")
# Comment out the above line once you've installed kent's package!

library(summarywidget)

knitr::opts_chunk$set(echo = FALSE, warning = F, message = F)

# Read in data
d = readxl::read_excel("output/data_both_projects_rolled_up.xlsx")

# Set up a shared data object; we'll use this to make plots and filters that are connected.
shared_d = crosstalk::SharedData$new(d)
```

Column {data-width=150}
--------------------------------------------------

### Filters and Info
```{r filters}
# Define our data filters (3 of them), and put them together into one column using the bscols() function. Note that we actually put the filters into one list(), and add an empty list() before and after our filter list... what a mess! This nonsense is necessary to make sure there is enough blank space on the left and right of our filters.
bscols(
  widths = c(1,8,1),
  list(),
  list(
    crosstalk::filter_select(
      "project","Project", shared_d, ~project,
    ),
    crosstalk::filter_slider(
      "date","Date", shared_d, ~date
    )
  ),
  list()
)
```

```{r plotting_function}

```

#### Title

Extra text.

Column {data-width=750}
--------------------------------------------

### Linked Figure {.tabset}
```{r linked_figure, fig.height=6}
shared_d |> 
  dplyr::group_by(project, year, basin, class.name, month) |> 
  dplyr::summarise(DB.cells.ml = sum(DB.cells.ml, na.rm=T),
                   LV.cells.ml = sum(LV.cells.ml, na.rm=T)) |> 
  plot_ly(, x = ~month, y = ~DB.cells.ml)
```

#### Goop
```{r}

```

#### Moop
```{r}

```

#### Doop
```{r}

```
